FROM node:14-slim
RUN apt-get update && apt-get install -y \
    vim libssl-dev git locales curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN echo "source /usr/share/bash-completion/completions/git" >> ~/.bashrc
RUN echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen ja_JP.UTF-8 && \
    /usr/sbin/update-locale LANG=ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
CMD ["/bin/bash"]
