version: "3.9"
services:
  postgres:
    image: postgres:13.2
    container_name: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      retries: 30

  pgadmin4:
    image: dpage/pgadmin4:5
    container_name: pgadmin
    ports:
      - 20080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@dummy.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  dev-api:
    build:
      context: ./api
    volumes:
      - ./api-env:/temp/api-env
      - ./init.sh:/temp/init.sh
      - workspace:/workspace
    ports:
      - 3010:3010
    networks:
      - postgres
      - application
    tty: true
    stdin_open: true
    secrets:
      - sshkey
    command: >
      bash -c '
        git config --global user.email "$GIT_USER_EMAIL" &&
        git config --global user.name "$GIT_USER_NAME" &&
        cp /run/secrets/sshkey ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa &&
        cat /temp/init.sh | tr -d "\r" | /bin/bash &&
        bash
      '

secrets:
  sshkey:
    file: ~/.ssh/id_rsa
volumes:
  database:
    driver: local
  pgadmin:
    driver: local
  workspace:
    driver: local
networks:
  application:
    driver: bridge
  postgres:
    driver: bridge
